#!/bin/bash
                        echo "Please Wait....."
                        count=1
                        #echo "---------------------------------------------" > /home/vps/public_html/new_expuser.txt
                        cat /etc/passwd | cut -d: -f1 > /tmp/alluser.txt
                        cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
                        totalaccounts=`cat /tmp/expirelist.txt | wc -l`
                        for((i=1; i<=$totalaccounts; i++ )); do
                        tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
                                username=`echo $tuserval | cut -f1 -d:`
                                userexp=`echo $tuserval | cut -f2 -d:`
                                userexpireinseconds=$(( $userexp * 86400 ))
                                todaystime=`date +%s`
                                expired="$(chage -l $username | grep "Account expires" | awk -F": " '{print $2}')"
                                if [ $userexpireinseconds -lt $todaystime ] ; then
                                        passwd -l $username > /dev/null 2>&1
                                        userdel $username > /dev/null
                                        egrep "^$username" /etc/passwd >/dev/null
                                        SELLER="$(getent passwd $username | cut -d ':' -f 5 | cut -d ',' -f 1)"
                                        printf "%-4s %-15s %-10s %-3s\n" "  " "$username" "$SELLER" "$expired" >> /home/vps/public_html/new_expuser.txt
                                        count=$((count+1))

                                fi
                                done
                                rm -r /tmp/*.txt

                                cat /home/vps/public_html/expuser.txt >> /home/vps/public_html/new_expuser.txt
                                rm /home/vps/public_html/expuser.txt
                                mv /home/vps/public_html/new_expuser.txt /home/vps/public_html/expuser.txt
                        # List Expired ID
                        clear
echo -e "=================== Information ========================"
echo -e "*                                                      *"
echo -e "*           Script Created By KingKongVPN              *"
echo -e "*              WhatsApp: +60178760080                  *"
echo -e "*              Telegram: @xiihaiqal                    *"
echo -e "*                                                      *"
echo -e "=================== Information ========================"
echo -e ""
echo "    ============================================="
echo "    * USERNAME                  EXPIRED DATE    *"
echo "    ============================================="
sed -n 1,20p /home/vps/public_html/expuser.txt
echo -e "=========================================================";

