#!/bin/bash
# Script Created By KingKongVPN
clear
echo -e "=================== Information ========================"
echo -e "*                                                      *"
echo -e "*           Script Created By HoraPusaVPN              *"
echo -e "*              Telegram: @hora_pusa                    *"
echo -e "*                                                      *"
echo -e "=================== Information ========================"
echo -e ""
echo -e "    ================================================"
read -p "      Enter Username To Be Remove : " Pengguna
echo -e "    ================================================"
clear
if getent passwd $Pengguna > /dev/null 2>&1; then
        userdel $Pengguna
                echo -e "=================== Information ========================"
                echo -e "*                                                      *"
                echo -e "*           Script Created By HoraPusaVPN              *"
                echo -e "*              Telegram: @hora_pusa                    *"
                echo -e "*                                                      *"
                echo -e "=================== Information ========================"
                echo -e ""
        echo -e "    ================== Hore ! ======================"
        echo -e "    *   Succesfully Delete User : $Pengguna        *"
        echo -e "    ================== Hore ! ======================"
                echo -e ""
else
                echo -e "=================== Information ========================"
                echo -e "*                                                      *"
                echo -e "*           Script Created By HoraPusaVPN              *"
                echo -e "*              Telegram: @hora_pusa                    *"
                echo -e "*                                                      *"
                echo -e "=================== Information ========================"
                echo -e ""
        echo -e "    ================ Yah Eror ! ===================="
        echo -e "    *   Username $Pengguna Does Not Exist ..!      *"
        echo -e "    ================ Yah Eror ! ===================="
                echo -e ""
fi
