#!/bin/bash
# ******************************************
# Program: Autoscript Setup VPS 2021
# Developer: HORAPUSA
# Nickname: HORAPUSA
# Modify : @hora_pusa
# Date: 02-08-2021
# Last Updated: 02-08-2021
# ******************************************
color1='\e[031;1m'
color2='\e[34;1m'
color3='\e[0m'

clear
echo -e "${color1}========================================${color3}"
echo -e "* ${color2}SCRIPT AUTO INSTALL BY HORAPUSA ${color3}*"
echo -e "${color1}========================================${color3}"
echo -e " "
echo -e "This Menu Still Under Development,Please Use Menu 1"
rm 'Menu 2'
